---
apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: grafana
type: Opaque
data:
#Understand these credentials are mentioned in the README.md to be changed, these are here for example purposes only.
  admin-user: YWRtaW4= 
  admin-password: ZGV2b3BzMTIz

#user/pass are encoded in base64, you can make your own with cmd
#$ echo -n "example-user" | base64

#To decode use the following cmd
#$ echo -n "ZXhhbXBsZS11c2Vy" | base64

#You will then use the decoded value to login into Grafana